package settings

import "fmt"

// ValidationError captures a specific constraint violation.
type ValidationError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// Sanitize brings the provided settings within supported ranges (mutates in place).
func Sanitize(s *Settings) {
	if s == nil {
		return
	}
	// Discovery
	// Minimum 1 minute for minutes-based interval
	if s.Discovery.MetricsRescanIntervalMinutes < 1 {
		s.Discovery.MetricsRescanIntervalMinutes = 1
	}
	if s.Discovery.MetricsRescanIntervalMinutes > 1440 {
		s.Discovery.MetricsRescanIntervalMinutes = 1440
	}
	// Seconds-based interval: minimum 15 seconds, max 300 (5 min)
	// If seconds is set to 0, minutes-based interval is used
	if s.Discovery.MetricsRescanIntervalSeconds > 0 {
		if s.Discovery.MetricsRescanIntervalSeconds < 15 {
			s.Discovery.MetricsRescanIntervalSeconds = 15
		}
		if s.Discovery.MetricsRescanIntervalSeconds > 300 {
			s.Discovery.MetricsRescanIntervalSeconds = 300
		}
	}
	if s.Discovery.Concurrency < 1 {
		s.Discovery.Concurrency = 1
	}
	if s.Discovery.Concurrency > 200 {
		s.Discovery.Concurrency = 200
	}
	// SNMP
	if s.SNMP.TimeoutMS < 500 {
		s.SNMP.TimeoutMS = 500
	}
	if s.SNMP.TimeoutMS > 60000 {
		s.SNMP.TimeoutMS = 60000
	}
	if s.SNMP.Retries < 0 {
		s.SNMP.Retries = 0
	}
	if s.SNMP.Retries > 5 {
		s.SNMP.Retries = 5
	}
	// Web
	if s.Web.HTTPPort == "" {
		s.Web.HTTPPort = DefaultSettings().Web.HTTPPort
	}
	if s.Web.HTTPSPort == "" {
		s.Web.HTTPSPort = DefaultSettings().Web.HTTPSPort
	}
}

// Validate ensures settings satisfy constraints; returns slice of violations.
func Validate(s Settings) []ValidationError {
	Sanitize(&s)
	var issues []ValidationError
	if s.Discovery.ManualRanges && s.Discovery.RangesText == "" {
		issues = append(issues, ValidationError{Field: "discovery.ranges_text", Message: "manual ranges enabled but no ranges text provided"})
	}
	if s.Web.EnableHTTPS && (s.Web.CustomCertPath == "" || s.Web.CustomKeyPath == "") {
		// Allow autogenerated cert paths by leaving empty; warn but not error.
	}
	return issues
}

// MergeDiscovery applies overrides to a base DiscoverySettings instance.
func MergeDiscovery(base DiscoverySettings, override DiscoverySettings) DiscoverySettings {
	result := base
	result.SubnetScan = override.SubnetScan
	result.ManualRanges = override.ManualRanges
	if override.RangesText != "" {
		result.RangesText = override.RangesText
	}
	if override.DetectedSubnet != "" {
		result.DetectedSubnet = override.DetectedSubnet
	}
	result.IPScanningEnabled = override.IPScanningEnabled
	if override.Concurrency != 0 {
		result.Concurrency = override.Concurrency
	}
	result.ARPEnabled = override.ARPEnabled
	result.ICMPEnabled = override.ICMPEnabled
	result.TCPEnabled = override.TCPEnabled
	result.SNMPEnabled = override.SNMPEnabled
	result.MDNSEnabled = override.MDNSEnabled
	result.AutoDiscoverEnabled = override.AutoDiscoverEnabled
	result.AutosaveDiscoveredDevices = override.AutosaveDiscoveredDevices
	result.ShowDiscoverButtonAnyway = override.ShowDiscoverButtonAnyway
	result.ShowDiscoveredDevicesAnyway = override.ShowDiscoveredDevicesAnyway
	result.PassiveDiscoveryEnabled = override.PassiveDiscoveryEnabled
	result.AutoDiscoverLiveMDNS = override.AutoDiscoverLiveMDNS
	result.AutoDiscoverLiveWSD = override.AutoDiscoverLiveWSD
	result.AutoDiscoverLiveSSDP = override.AutoDiscoverLiveSSDP
	result.AutoDiscoverLiveSNMPTrap = override.AutoDiscoverLiveSNMPTrap
	result.AutoDiscoverLiveLLMNR = override.AutoDiscoverLiveLLMNR
	if override.MetricsRescanIntervalMinutes != 0 {
		result.MetricsRescanIntervalMinutes = override.MetricsRescanIntervalMinutes
	}
	if override.MetricsRescanIntervalSeconds != 0 {
		result.MetricsRescanIntervalSeconds = override.MetricsRescanIntervalSeconds
	}
	result.MetricsRescanEnabled = override.MetricsRescanEnabled
	return result
}

// Merge combines two Settings structs, giving precedence to overrides.
func Merge(base Settings, override Settings) Settings {
	merged := base
	merged.Discovery = MergeDiscovery(base.Discovery, override.Discovery)
	merged.SNMP = override.SNMP
	merged.Features = override.Features
	merged.Logging = override.Logging
	merged.Web = override.Web
	Sanitize(&merged)
	return merged
}

// MustValidate panics if settings fail validation (helper for tests / bootstrapping).
func MustValidate(s Settings) {
	if issues := Validate(s); len(issues) > 0 {
		panic(fmt.Sprintf("invalid settings: %#v", issues))
	}
}
