package settings

import "fmt"

// ValidationError captures a specific constraint violation.
type ValidationError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// Sanitize brings the provided settings within supported ranges (mutates in place).
func Sanitize(s *Settings) {
	if s == nil {
		return
	}
	if s.Discovery.MetricsRescanIntervalMinutes < 5 {
		s.Discovery.MetricsRescanIntervalMinutes = 5
	}
	if s.Discovery.MetricsRescanIntervalMinutes > 1440 {
		s.Discovery.MetricsRescanIntervalMinutes = 1440
	}
	if s.Developer.SNMPTimeoutMS < 500 {
		s.Developer.SNMPTimeoutMS = 500
	}
	if s.Developer.SNMPTimeoutMS > 60000 {
		s.Developer.SNMPTimeoutMS = 60000
	}
	if s.Developer.SNMPRetries < 0 {
		s.Developer.SNMPRetries = 0
	}
	if s.Developer.SNMPRetries > 5 {
		s.Developer.SNMPRetries = 5
	}
	if s.Developer.DiscoverConcurrency < 1 {
		s.Developer.DiscoverConcurrency = 1
	}
	if s.Developer.DiscoverConcurrency > 200 {
		s.Developer.DiscoverConcurrency = 200
	}
	if s.Security.HTTPPort == "" {
		s.Security.HTTPPort = DefaultSettings().Security.HTTPPort
	}
	if s.Security.HTTPSPort == "" {
		s.Security.HTTPSPort = DefaultSettings().Security.HTTPSPort
	}
}

// Validate ensures settings satisfy constraints; returns slice of violations.
func Validate(s Settings) []ValidationError {
	Sanitize(&s)
	var issues []ValidationError
	if s.Discovery.ManualRanges && s.Discovery.RangesText == "" {
		issues = append(issues, ValidationError{Field: "discovery.ranges_text", Message: "manual ranges enabled but no ranges text provided"})
	}
	if s.Security.EnableHTTPS && (s.Security.CustomCertPath == "" || s.Security.CustomKeyPath == "") {
		// Allow autogenerated cert paths by leaving empty; warn but not error.
	}
	return issues
}

// MergeDiscovery applies overrides to a base DiscoverySettings instance.
func MergeDiscovery(base DiscoverySettings, override DiscoverySettings) DiscoverySettings {
	result := base
	result.SubnetScan = override.SubnetScan
	result.ManualRanges = override.ManualRanges
	if override.RangesText != "" {
		result.RangesText = override.RangesText
	}
	if override.DetectedSubnet != "" {
		result.DetectedSubnet = override.DetectedSubnet
	}
	result.IPScanningEnabled = override.IPScanningEnabled
	result.ARPEnabled = override.ARPEnabled
	result.ICMPEnabled = override.ICMPEnabled
	result.TCPEnabled = override.TCPEnabled
	result.MDNSEnabled = override.MDNSEnabled
	result.SNMPEnabled = override.SNMPEnabled
	result.AutoDiscoverEnabled = override.AutoDiscoverEnabled
	result.AutosaveDiscoveredDevices = override.AutosaveDiscoveredDevices
	result.ShowDiscoverButtonAnyway = override.ShowDiscoverButtonAnyway
	result.ShowDiscoveredDevicesAnyway = override.ShowDiscoveredDevicesAnyway
	result.PassiveDiscoveryEnabled = override.PassiveDiscoveryEnabled
	result.AutoDiscoverLiveMDNS = override.AutoDiscoverLiveMDNS
	result.AutoDiscoverLiveWSD = override.AutoDiscoverLiveWSD
	result.AutoDiscoverLiveSSDP = override.AutoDiscoverLiveSSDP
	result.AutoDiscoverLiveSNMPTrap = override.AutoDiscoverLiveSNMPTrap
	result.AutoDiscoverLiveLLMNR = override.AutoDiscoverLiveLLMNR
	if override.MetricsRescanIntervalMinutes != 0 {
		result.MetricsRescanIntervalMinutes = override.MetricsRescanIntervalMinutes
	}
	result.MetricsRescanEnabled = override.MetricsRescanEnabled
	return result
}

// Merge combines two Settings structs, giving precedence to overrides.
func Merge(base Settings, override Settings) Settings {
	merged := base
	merged.Discovery = MergeDiscovery(base.Discovery, override.Discovery)
	merged.Developer = override.Developer
	merged.Security = override.Security
	Sanitize(&merged)
	return merged
}

// MustValidate panics if settings fail validation (helper for tests / bootstrapping).
func MustValidate(s Settings) {
	if issues := Validate(s); len(issues) > 0 {
		panic(fmt.Sprintf("invalid settings: %#v", issues))
	}
}
